/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stackcalculator;

import javax.swing.JOptionPane;
import java.util.Stack;
/**
 *
 * @author Jane Justine
 */
public class java extends javax.swing.JFrame {
     private Stack<Double> stack;
    /**
     * Creates new form StackCalculator
     */
 public java() {
      initComponents(); // Initializes components
        stack = new Stack<>(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButtonnum7 = new javax.swing.JButton();
        jButtonnum9 = new javax.swing.JButton();
        jButtonnum8 = new javax.swing.JButton();
        jButtonopdiv = new javax.swing.JButton();
        jButtonnum4 = new javax.swing.JButton();
        jButtonnum5 = new javax.swing.JButton();
        jButtonnum6 = new javax.swing.JButton();
        jButtonopmul = new javax.swing.JButton();
        jButtonnum1 = new javax.swing.JButton();
        jButtonnum2 = new javax.swing.JButton();
        jButtonnum3 = new javax.swing.JButton();
        jButtonopsub = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();
        jButtonopadd = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButtonpush = new javax.swing.JButton();
        jButtonnum0 = new javax.swing.JButton();
        jButtonpeek = new javax.swing.JButton();
        jButtonpop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STACK CALCULATOR");
        setResizable(false);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButtonnum7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnum7.setText("7");
        jButtonnum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnum7ActionPerformed(evt);
            }
        });

        jButtonnum9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnum9.setText("9");
        jButtonnum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnum9ActionPerformed(evt);
            }
        });

        jButtonnum8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnum8.setText("8");
        jButtonnum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnum8ActionPerformed(evt);
            }
        });

        jButtonopdiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonopdiv.setText("/");
        jButtonopdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonopdivActionPerformed(evt);
            }
        });

        jButtonnum4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnum4.setText("4");
        jButtonnum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnum4ActionPerformed(evt);
            }
        });

        jButtonnum5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnum5.setText("5");
        jButtonnum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnum5ActionPerformed(evt);
            }
        });

        jButtonnum6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnum6.setText("6");
        jButtonnum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnum6ActionPerformed(evt);
            }
        });

        jButtonopmul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonopmul.setText("*");
        jButtonopmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonopmulActionPerformed(evt);
            }
        });

        jButtonnum1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnum1.setText("1");
        jButtonnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnum1ActionPerformed(evt);
            }
        });

        jButtonnum2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnum2.setText("2");
        jButtonnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnum2ActionPerformed(evt);
            }
        });

        jButtonnum3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnum3.setText("3");
        jButtonnum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnum3ActionPerformed(evt);
            }
        });

        jButtonopsub.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonopsub.setText("-");
        jButtonopsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonopsubActionPerformed(evt);
            }
        });

        jButtonclear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonclear.setText("C");
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        jButtonopadd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonopadd.setText("+");
        jButtonopadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonopaddActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButtonpush.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonpush.setText("PUSH");
        jButtonpush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpushActionPerformed(evt);
            }
        });

        jButtonnum0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnum0.setText("0");
        jButtonnum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnum0ActionPerformed(evt);
            }
        });

        jButtonpeek.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonpeek.setText("PEEK");
        jButtonpeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpeekActionPerformed(evt);
            }
        });

        jButtonpop.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonpop.setText("POP");
        jButtonpop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonnum4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonnum5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonnum6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonnum9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonnum3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonnum7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jButtonnum8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonopsub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonopdiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonopmul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonnum0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonopadd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonpush)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonpeek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonpop, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnum7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonnum8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonnum9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonopdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnum4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonnum5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonnum6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonopmul, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnum3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonopsub, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnum0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonopadd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonpush, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonpeek, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonpop, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonnum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnum9ActionPerformed
         handleNumberButtonClick(9);
    }//GEN-LAST:event_jButtonnum9ActionPerformed

    private void jButtonnum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnum8ActionPerformed
  handleNumberButtonClick(8);
    }//GEN-LAST:event_jButtonnum8ActionPerformed

    private void jButtonnum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnum7ActionPerformed
         handleNumberButtonClick(7);
    }//GEN-LAST:event_jButtonnum7ActionPerformed

    private void jButtonopdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonopdivActionPerformed
         performOperation("/");
    }//GEN-LAST:event_jButtonopdivActionPerformed

    private void jButtonnum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnum4ActionPerformed
        handleNumberButtonClick(4);
    }//GEN-LAST:event_jButtonnum4ActionPerformed

    private void jButtonnum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnum5ActionPerformed
        handleNumberButtonClick(5);
    }//GEN-LAST:event_jButtonnum5ActionPerformed

    private void jButtonnum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnum6ActionPerformed
         handleNumberButtonClick(6);
    }//GEN-LAST:event_jButtonnum6ActionPerformed

    private void jButtonopmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonopmulActionPerformed
      performOperation("*");
    }//GEN-LAST:event_jButtonopmulActionPerformed

    private void jButtonnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnum1ActionPerformed
        handleNumberButtonClick(1);
    }//GEN-LAST:event_jButtonnum1ActionPerformed

    private void jButtonnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnum2ActionPerformed
        handleNumberButtonClick(2);
    }//GEN-LAST:event_jButtonnum2ActionPerformed

    private void jButtonnum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnum3ActionPerformed
       handleNumberButtonClick(3);
    }//GEN-LAST:event_jButtonnum3ActionPerformed

    private void jButtonopsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonopsubActionPerformed
        performOperation("-");
    }//GEN-LAST:event_jButtonopsubActionPerformed

    private void jButtonnum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnum0ActionPerformed
        handleNumberButtonClick(0);
    }//GEN-LAST:event_jButtonnum0ActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        stack.clear(); // Clear the stack
        jTextField4.setText(""); // Clear the display
    }//GEN-LAST:event_jButtonclearActionPerformed

    private void jButtonpushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpushActionPerformed
      try {
        // Get user input from jTextField4
        double value = Double.parseDouble(jTextField4.getText()); 

        // Check if all fields are filled
        if (!jTextField1.getText().isEmpty() && 
            !jTextField2.getText().isEmpty() && 
            !jTextField3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cannot push: All fields are full!");
            jTextField4.setText("");  // Clear jTextField4 if unable to push
            return;
        }
        // Shift values upwards
        jTextField1.setText(jTextField2.getText());  
        jTextField2.setText(jTextField3.getText());  
        jTextField3.setText(String.valueOf(value));  // Display new value in jTextField3

        // Push the value onto the stack
        stack.push(value);  // Only the value pushed from jTextField4 should go to the stack

        // Clear the input field for new input
        jTextField4.setText("");  

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid number.");
    }
    }//GEN-LAST:event_jButtonpushActionPerformed

    private void jButtonopaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonopaddActionPerformed
        performOperation("+");
    }//GEN-LAST:event_jButtonopaddActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonpeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpeekActionPerformed
         // Check if jTextField3 is empty before trying to peek
    if (jTextField3.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Stack is empty, nothing to peek.");
    } else {
        // Safely parse the top value from jTextField3
        double topValue = Double.parseDouble(jTextField3.getText());
        // Display the top value in a JOptionPane message
        JOptionPane.showMessageDialog(this, "Top item of the stack: " + topValue);
    }
    }//GEN-LAST:event_jButtonpeekActionPerformed

    private void jButtonpopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpopActionPerformed
      // Check if the stack is empty (by checking if jTextField3 is empty)
    if (jTextField3.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nothing to pop: Stack is empty.");
        return;
    }

    // Get the current top value from jTextField3 to show in the message
    double poppedValue = Double.parseDouble(jTextField3.getText()); 

    // Show a message with the popped value
    JOptionPane.showMessageDialog(this, "Popped element: " + poppedValue);

    // Shift values downwards
    jTextField3.setText(jTextField2.getText()); // Move value from jTextField2 to jTextField3 (new top)
    jTextField2.setText(jTextField1.getText()); // Move value from jTextField1 to jTextField2
    jTextField1.setText("");

    }//GEN-LAST:event_jButtonpopActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
  private void handleNumberButtonClick(int number) {
        // Push the number to the stack and display it
        stack.push((double) number);
        jTextField4.setText(String.valueOf(stack.peek())); // Display top of the stack
    }
  
    private void performOperation(String op) {
        if (stack.isEmpty()) {
            return; // Prevent operation if stack is empty
        }
        double secondOperand = stack.pop(); // Pop the top two operands
        if (stack.isEmpty()) {
            stack.push(secondOperand); // Push it back if there's no second operand
            return;
        }
        double firstOperand = stack.pop();
        double result = 0;

        switch (op) {
            case "+":
                result = firstOperand + secondOperand;
                break;
            case "-":
                result = firstOperand - secondOperand;
                break;
            case "*":
                result = firstOperand * secondOperand;
                break;
            case "/":
                if (secondOperand == 0) {
                    JOptionPane.showMessageDialog(this, "Cannot divide by zero!");
                    stack.push(firstOperand); // Push back the operands
                    stack.push(secondOperand);
                    return;
                }
                result = firstOperand / secondOperand;
                break;
        }
        stack.push(result); // Push the result back onto the stack
        jTextField4.setText(String.valueOf(result)); // Display the result
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StackCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StackCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StackCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StackCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StackCalcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtonnum0;
    private javax.swing.JButton jButtonnum1;
    private javax.swing.JButton jButtonnum2;
    private javax.swing.JButton jButtonnum3;
    private javax.swing.JButton jButtonnum4;
    private javax.swing.JButton jButtonnum5;
    private javax.swing.JButton jButtonnum6;
    private javax.swing.JButton jButtonnum7;
    private javax.swing.JButton jButtonnum8;
    private javax.swing.JButton jButtonnum9;
    private javax.swing.JButton jButtonopadd;
    private javax.swing.JButton jButtonopdiv;
    private javax.swing.JButton jButtonopmul;
    private javax.swing.JButton jButtonopsub;
    private javax.swing.JButton jButtonpeek;
    private javax.swing.JButton jButtonpop;
    private javax.swing.JButton jButtonpush;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}